> Initialized logger
>  * Debugger is active!
>  * Debugger PIN: 132-496-986
> Exception in thread Malaria Detection:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
>     self.run()
>   File "/home/aisilverb/Desktop/remidiv2/serveus/darknet/detector.py", line 69, in run
>     self.query()
>   File "/home/aisilverb/Desktop/remidiv2/serveus/darknet/detector.py", line 87, in query
>     self.detector(str('~/Desktop/remidiv2/upload/'+chunklist.filename)+'/'+img, image.id)
>   File "/home/aisilverb/Desktop/remidiv2/serveus/darknet/detector.py", line 111, in detector
>     savetodb(img_id, jsonfile)
> NameError: global name 'savetodb' is not defined
>  * Detected change in '/home/aisilverb/Desktop/remidiv2/serveus/darknet/detector.py', reloading
